# Generated by Django 6.1.1 on 2026-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name (e.g., my-awesome-project)', max_length=250, unique=True)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated list (e.g., Django, React, PostgreSQL)', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_projects/')),
                ('live_preview_url', models.URLField(blank=True, null=True, verbose_name='Live Preview Link')),
                ('source_code_url', models.URLField(blank=True, null=True, verbose_name='GitHub/Source Link')),
                ('date_completed', models.DateField()),
                ('is_featured', models.BooleanField(default=False, help_text='Check this to highlight the project on your homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
