# Generated by Django 6.1.1 on 2026-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_projects/')),
                ('live_preview_url', models.URLField(blank=True, null=True)),
                ('source_code_url', models.URLField(blank=True, null=True)),
                ('date_completed', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
